"""Added user foreign key to student_marks

Revision ID: 6fb0778351fe
Revises: 021589037aae
Create Date: 2024-11-27 14:39:16.355370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb0778351fe'
down_revision: Union[str, None] = '021589037aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_marks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_marks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_marks', type_='foreignkey')
    op.drop_column('student_marks', 'user_id')
    # ### end Alembic commands ###
