"""Initial migration

Revision ID: 8d2f02472a9c
Revises: 
Create Date: 2024-12-02 12:40:54.736414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2f02472a9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

examstatus_enum = sa.Enum('completed', 'scheduled', name='examstatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('status', examstatus_enum, nullable=True))
    op.add_column('exams', sa.Column('teacher_name', sa.String(), nullable=False ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'teacher_name')
    op.drop_column('exams', 'status')
    # ### end Alembic commands ###
