"""Add test_paper to exams table

Revision ID: 90fd1f02751a
Revises: 6fb0778351fe
Create Date: 2024-11-28 18:04:57.322093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fd1f02751a'
down_revision: Union[str, None] = '6fb0778351fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('test_paper', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'test_paper')
    # ### end Alembic commands ###
